### ISSUE TITLE
HANS title booting doesn't work if background loading isn't finished

### ISSUE THREAD

**Issue by ihaveamac** [mashers/3ds_hb_menu#10]
if HANS title booting is enabled, and a title is selected in the launcher before background loading finishes, then the launcher freezes (sometimes does nothing, sometimes shows red screen).

if all the titles have been loaded, or HANS is used standalone, it works as intended, like any other homebrew using the title selector.

tested on beta 108

might not be relevant but included anyway: New (ironhax) and Old (oot3dhax) 3DS. 2.5 payload date is 2015-11-09.

**Comment by mashers** [comment]
Sorted - I forgot to terminate and release the background thread when booting using HANS. Good catch buddy! :)
