### ISSUE TITLE
Titles not loading up when launching some apps that need to select a title to run.

### ISSUE THREAD

**Issue by JJTapia19** [mashers/3ds_hb_menu#28]
Some apps like the new retroarch mame emulator once you select it from the HBL the select title screen shows up, then you must select the title you have on your .xml file next to it's .3dsx. The problem is that once you select the app from the HBL the select title screen appears but the titles are not loading up.

Workaround:
If you load up the titles first with the title selector or any other app and then open the emulator, the titles appear like they should.

Here I'll leave a link to the emulator. Mine haves Monster Hunter 4 Demo configured on the .xml but that only matters when booting the app after selecting the needed title so if you don't have the demo you should still be able to reproduce the problem.

Retroarch Mame: https://mega.nz/#!us5k1ALA!igKU0IouAOAPqskifma7ND6nIZQctUKtcp9BldS-Ft4

**Comment by JJTapia19** [comment]
My setup is
New 3DS version 9.0
3DS region: US
Entrypoint: Homemenuhax
Hax version: 2.5

**Comment by mashers** [comment]
Thanks buddy. I think it's sorted but don't know how to use the app in question so can't get any titles to actually boot. Could you try with boot1.3dsx from this commit please?

https://github.com/mashers/3ds_hb_menu/issues/28#ref-commit-9a2efc2

**Comment by JJTapia19** [comment]
It worked! Thanks for fixing it. The emulator only works with some specific titles like mh4 demo, youtube and a couple more I can't remember. Maybe that's why the titles did not booted for you. It took me a while to figure it out.

**Comment by mashers** [comment]
Great, thank you for confirming! I'll add this to the next beta :)
