### ISSUE TITLE
No body text appears for Reboot screen

### ISSUE THREAD

**Issue by ihaveamac** [mashers/3ds_hb_menu#32]
beta 111. no idea if this is intentional since #30 
![nothing below "Reboot"](http://i.imgur.com/pqQE58o.png)

**Comment by ihaveamac** [comment]
I'm no expert at C (or don't really know any) but [these lines without brackets](https://github.com/mashers/3ds_hb_menu/blob/master/source/main.c#L255-L256) look suspicious...

**Comment by mashers** [comment]
Definitely not intentional. And no unfortunately it's not as simple as missing brackets. I have no idea why it's not there, but I've labelled this as a bug and will look into it today. Thanks!
