### ISSUE TITLE
Cursor loss in Folder menu in b111

### ISSUE THREAD

**Issue by Goombi** [mashers/3ds_hb_menu#33]
If you place the cursor on a corner button in the Folder menu and press down to go back on the grid, the cursor will dissapear if you were on the "Back" button and on the 3rd column if you were on the "Option" button.

Not tested, can't compile it due to wrong types in boot.c...?
Anyway, seems to be around here:
menu.c:1349
folders.c:125
You commented the increases of numEntries in the folder menu. Then we have first = 0 and numEntries = 0, so you place the cursor at 0-1 since 0>=0. And since you add 3 when going down from the right corner button, that ends up on the 3rd column.
Could be wrong though, can't compile anymore to check. Are you using latest ctrulib?

**Comment by mashers** [comment]
Confirmed, I can reproduce this bug. I'll investigate today. Thanks for the report :)
