### ISSUE TITLE
Add descriptions for new features to Readme.md

### ISSUE THREAD

**Issue by d0k3** [mashers/3ds_hb_menu#38]
The grid launcher, by now, has a lot of features that smealums launcher does not have, things like, f.e. the splash screen or the reboot splash screen. While most of these features are self explanatory, some are not (ie, for the splash screen, I can't find out on myself how to call that file). Descriptions for these new features are now (to my knowledge) only found in the changelog and buried deep in the thread.

So... could you add (short, if anyone doesn't understand he may still ask in thread) descriptions for these features to the readme.md?

**Comment by ihaveamac** [comment]
here's a list of image files I've gathered from the first post by searching ".png", along with resolutions. no organization done yet, just went from bottom to top.
* wallpapertop.png - 400x240, no alpha channel
* wallpaperbottom.png - 320x240, no alpha channel
* appbackground.png - 56x56
* appbackgroundselected.png - 56x56
* cartbackground.png - 59x59
* cartbackgroundselected.png - 59x59
* buttontopleft.png - 36x36
* buttontopleftselected.png - 36x36
* buttontopright.png - 36x36
* buttontoprightselected - 36x36
* buttonbottomleft.png - 36x36
* buttonbottomleftselected.png - 36x36
* buttonbottomright.png - 36x36
* buttonbottomrightselected.png - 36x36
* backicon.png - 36x36
* foldersicon.png - 36x36
* helpicon.png - 36x36
* homeicon.png - 36x36
* settingsicon.png - 36x36
* wallpapertopinfo.png - 400x240, no alpha channel
* wallpaperbottomnongrid.png - 320x240, no alpha channel
* progressWheelFrame1.png ... progressWheelFrame6.png - 36x36
* splashtop.png - 400x240, no alpha channel
* splashbottom.png - 320x240, no alpha channel
* wallpapertopreboot.png - 400x240, no alpha channel
* wallpaperbottomreboot.png - 320x240, no alpha channel

**Comment by mashers** [comment]
That was a comprehensive list of all of the images - thanks! I've edited your post to sort them. I also corrected the progress wheel frames (you can now have up to 16), and also removed the bit about no alpha channel on wallpapers as this is now supported.

**Comment by RedInquisitive** [comment]
I have had quite the list typed up here for a while: https://github.com/RedInquisitive/3DS-Homebrew-Menu/tree/master/gridlauncher/themes but @ihaveamac covered basically all of it there.

**Comment by mashers** [comment]
There's also JJTapia19's thread on GBATemp which summarises a lot of this information into a themes guide. I think we need to draw all of this information together into a central location but I'm not really sure where it should be.

**Comment by ihaveamac** [comment]
maybe inside README.md, or a separate Themes.md/THEMING.md/etc.? it could be linked to in the main post as well.

**Comment by ihaveamac** [comment]
going to "bump" this issue, saying that the information could go to `/gridlauncher/themes/README.md`. it would also be included in launcher.zip.

**Comment by mashers** [comment]
This is now covered by the Wiki so I'm closing this issue.
