### ISSUE TITLE
Add banners for carts and titles

### ISSUE THREAD

**Issue by mashers** [mashers/3ds_hb_menu#44]
Currently, banners only work for homebrew apps. Provision needs to be made for them to exist also for titles. This could work as follows:

* On startup, the launcher creates the folder /gridlauncher/titlebanners/
* Users place banner images in this folder using the filename <titleid>-banner.png
* When drawMenuEntry() is called, the menuEntry_s struct's title_id value is checked to see if there is a banner image for that title. If so, the same loading/drawing code can be used to draw the image

**Comment by JJTapia19** [comment]
Could you also implement banners to folders?

Quick example:
SD:gridlauncher/folders/Emulators/Emulators-banner.png

**Comment by mashers** [comment]
Ahh yes, good idea. I'll add that as a separate issue. Thanks!

**Comment by mashers** [comment]
Added in https://github.com/mashers/3ds_hb_menu/commit/9ed204118a271831a123c4b298a1ab8e881c434b
