### ISSUE TITLE
BIN format theme images with converter tool

### ISSUE THREAD

**Issue by mashers** [mashers/3ds_hb_menu#48]
If the images were stored in .bin format then the PNG code could be stripped out along with libpng, which would save a LOT of executable space. A converter app could then be written to take the existing folder structure and convert it to a packaged up theme with pre-converted images (PNG->bin). This would also make theme loading much faster as the PNG converting and image rotating would already be done.

**Comment by ihaveamac** [comment]
[just quoting my post:](https://gbatemp.net/threads/release-homebrew-launcher-with-grid-layout.397527/page-173#post-5819140)
>actually no, creating another format wouldn't be of much use I think. creating an *editor* for the *existing* one though would remove quite a bit of code from the launcher though.

if you'd like to keep the editor in though, that's fine.

**Comment by mashers** [comment]
Well, I still think a separate editor would be a good idea. However, introducing a custom format gives so many extra benefits:
* Pre-conversion from PNG to BIN will speed up file loading
* Lack of reliance on PNG files means that libpng can be removed from the launcher
* Pre-rotation by 90 degrees will speed up image loading a lot

The disadvantage of course is that it will be harder to modify themes which have already been converted. So a reverse converter which turns everything back into PNGs might also be needed.

**Comment by ihaveamac** [comment]
ok I'm misunderstanding this. this is just a custom format for images and the like. but the `hbltheme.cfg` containing colors and other options would remain, right?

**Comment by mashers** [comment]
I was actually thinking more along the lines of everything being packaged up into one file with a .theme extension. That will make it easier to install themes (just one file to copy). However, keeping to a folder containing multiple files would work just as well. In fact it might be more efficient since the file won't need to be scanned through for the files (then can be accessed directly by filename like now). So essentially what we're talking about is:
* Move theme settings to a separate app
* Include theme importer in this app. This will scan the theme folder for PNG files and convert them to .bin format
* Remove libpng and PNG loading code from the launcher
* Update theme loading code to load directly from .bin files

How does that sound?

**Comment by ihaveamac** [comment]
well I'm only a Lua person so I'm limited to what lpp-3ds can do (or I think there's another WIP interpreter). that should be taken into account. of course someone else can always step up if this is not what you want, and I would completely understand it.

one of my suggestions could be to look into different image formats (.bmp? .jpg?) and see how they compare. if one of them work out, then it would make the whole transition process easier for the end-user.

as for an editor, I'm sure I could do it. it probably won't look the same as the current editor, but would have the same features. do you have the original versions of the icons and other images (i.e. logos)?

**Comment by ihaveamac** [comment]
I'd just like to add here that I wanted to "mimic" the current theme settings like changing colors, toggling water and logo, etc. but if you use bmp/jpg then maybe. jpg might not be the best due to compression though.

**Comment by ihaveamac** [comment]
ah, I see they are in .pxm, or Pixelmator's image format. luckily I actually have Pixelmator from the mac app store so I can open them as well. :p

**Comment by mashers** [comment]
I think at this stage the priority needs to be a maximal reduction in the amount of code used in the launcher and a maximal increase in the efficiency of the image loading. My opinion is that the best way of achieving this is to have the images stored in a pre converted bin format. Even if we switched to a different image format (e.g. BMP), users would still need to convert the existing theme images to the new format. So a conversion tool could be created to convert existing themes to bin format images, and new themes too. It would be simple to check for png files when loading a theme and show the user a warning that they need need to run the converter on the theme.

With regards to an external theme editor, I think that this will be less necesary once libpng has been removed as it will free up a lot of space for code for new features. However, as you say the graphics assets are in Pixelmator format so feel free to work on this as it might be useful in the future,

Bear in mind though that the converter will need to be written in C as I doubt lua has access to libpng which is needed for the file conversion.

**Comment by ihaveamac** [comment]
>Bear in mind though that the converter will need to be written in C as I doubt lua has access to libpng which is needed for the file conversion.
lpp-3ds does have PNG support (lodepng), though I removed it from my heavily stripped version for the updater. it also supports BMP/JPG which is why I mentioned them, also because they're common formats. creating a separate converter program shouldn't be too difficult, though keep in mind it should be launched from the grid launcher.

how much code does the theme editor take up? the larger it is, the more likely it might be needed to split it off to a separate app, especially given it's not something accessed that often. it would also delay needing to find what to remove again for a while.

**Comment by mashers** [comment]
Does it have access to the raw png data? And would it be able to rotate the image? If so it could be used to convert the image.

I'm not sure how much space the editor takes up right now. There is a lot of code which is shared with other parts of the launcher and so would need to stay.

To be honest libpng is huge and removing it would make a significant difference to the amount of code available, so I would like to prioritise removing it.

**Comment by ihaveamac** [comment]
>Does it have access to the raw png data? And would it be able to rotate the image? If so it could be used to convert the image.

since we're doing a special format, it won't be able to help, so a separate program to do it would be better.

and a separate editor of course is not a priority, but I will still pursue it, albeit not so quickly. it'll give me something to do though.

**Comment by mashers** [comment]
I do think a separate editor would be good. Actually there's a request somewhere for XML layout of the UI. An external editor would be ideal for this!

**Comment by ihaveamac** [comment]
#29

XML, huh... I would think a format similar to .cfg would work (e.g. `time:50,50` or `timex:50|timey:50`), but XML should be fine as well. I think there are XML parsers created in only Lua, judging by [this page](http://lua-users.org/wiki/LuaXml), making them easy to implement. I would need some kind of specification though, like what the names and formats are.

of course I'll need a way to get the font used. an image of the text would be ideal maybe if it can be reproduced with a transparent background. lpp-3ds also supports fonts but I don't know if it'd match the grid launcher enough (should go check that right now!). I know it's using Roboto.

that would also make requiring a .png/.bmp/.jpg background for the editor unless somehow lpp-3ds can be modified to include support for this special format. it might be easier to just require the original format since only theme creators would really need to use it, and they would have the source images already.

**Comment by ihaveamac** [comment]
first and foremost, a "replica" of the current theme editor. if we're going to edit a part of the theme, might as well edit all of it. it will need lots of testing and changes before the one built in could be removed though.

also, I think if parts of the launcher get separated into apps, they should all go into something like  `/gridlauncher/tools` (*except the updater*). it'd be easier for the updater to get the latest versions of those without having to always manually add support for a new tool.

**Comment by RedInquisitive** [comment]
@mashers So you are looking to get rid of the PNG library, right? What if there was a tool that simply took current themes and converted all picture types (BMP, JPG, PNG) to a .bin file and copied it from your desktop and put it on the SD card. Of course people who already use themes will have to "recompile" all of there themes which could take some time, but is that what you are looking for?

Of course the problems (most of theme simple to solve) would be
- The tool would have to be updated whenever a theme feature is added
- Users would have to always be compiling there theme whenever they want to update it (maybe an on-3ds app to recompile themes to .bin format?)
- App would have to be cross platform for a desktop app batch processing (perhaps Java?)
- All existing themes would have to manually be recompiled.
- unforeseen issues.

IDK, this is probably a terrible idea, I was just brainstorming the current issue.

Wasn't there a suggestion from smea saying code could be moved into different .o files at a cost of performance. This was it I think: [gbatemp.net](https://gbatemp.net/threads/release-homebrew-launcher-with-grid-layout.397527/page-121#post-5775820)

**Comment by ihaveamac** [comment]
>The tool would have to be updated whenever a theme feature is added

as far as I know this is only for converting images, so this "tool" that just converts images likely won't need to be updated for every new feature.

>All existing themes would have to manually be recompiled.

I believe mashers wanted to make it on the 3DS so it's easier for users to convert their existing theme images over.

**Comment by mashers** [comment]
Yes, the idea is to remove the requirement for libpng to make space for new features. Also, the images will be pre-rotated which should save processing time.

Can't figure out how to quote on here, so I'll just copy and paste:

_The tool would have to be updated whenever a theme feature is added_
Actually the tool will just scan through for PNG files and convert them, so new theme features added in will automatically be converted by the tool.

_Users would have to always be compiling there theme whenever they want to update it (maybe an on-3ds app to recompile themes to .bin format?)_
Yes, if they add images to the theme then they will have to recompile. But the conversion tool will be on the 3DS and accessible directly from Gridlauncher (like the updater).

_App would have to be cross platform for a desktop app batch processing (perhaps Java?)_
See above - it will be on the 3DS itself.

_All existing themes would have to manually be recompiled._
True, but I'll add a check when loading a theme to see if there are any PNG files. If there are, a warning will be displayed to the user saying that PNG images were detected in the theme and that they should run the theme converter. The converter will check *all* themes for PNG images and convert them all, and then move the PNG images into a subfolder of the theme so they don't get re-detected.


I have rewritten the function which loads the theme images to load from bin files, and this works well with manually converted bin files. I am now working on the converter, and have got as far as scanning for themes, scanning each theme for files, identifying PNGs, loading them, rotating them and outputting to an array of u8. I now just need to get them saved to bin files and move the PNGs and the converter should be pretty much ready.

**Comment by mashers** [comment]
Oh, and WRT moving stuff to a lower-performance compilation mode, I would much rather give the user a one-off conversion tool which they run when they modify a theme. This way they just run the converter and it converts the theme, and then everything runs at optimal performance without the need for libpng.

**Comment by mashers** [comment]
Well, it looks like this idea is bust. Loading the theme images from .bin files actually takes **longer** than loading from PNGs. I suspect this is because the files are bigger (no compression?) In any case, it doesn't seem worth removing libpng as the detriment to performance when loading themes is massive. I'm therefore closing this enhancement suggestion and reverting back to using PNGs.

**Comment by ihaveamac** [comment]
disappointing. hope a solution for the size comes soon.

**Comment by mashers** [comment]
To be honest I'm hugely surprised at this outcome. I thought loading a slightly larger file which was pre-converted (and crucially pre-rotated) would be faster than doing the conversion from PNG on the fly. It would appear that the 3DS's CPU and memory access is much faster than its access to the SD card, meaning the tradeoff of loading a larger file isn't worth it.

For now we're ok in terms of capacity for new code as the screenshot feature was rather large so made a lot of space. I might look into a cutdown libPNG implementation as there are a lot of features of the full library which aren't used.

**Comment by ihaveamac** [comment]
yeah 3DS doesn't seem to have that fast SD access. I heard anything above a class 4 [micro]SD card doesn't do much. how big was the .bin compared to .png file you used?

**Comment by mashers** [comment]
I suspected as much. I've just checked, and wallpapertop (the largest image) was 170k in PNG format and 288k in bin format. That's a huge difference, especially if you consider the sheer number of images which can exist in a theme now.
