### ISSUE TITLE
SELECT shows the HANS/Region4 on homebrew apps

### ISSUE THREAD

**Issue by ihaveamac** [mashers/3ds_hb_menu#49]
press select while homebrew apps are listed and it will show the menu that lets you pick between HANS and Region4, which is meant for the title launcher.

both of them just launch the program as intended though. just though I'd "put that out there".

beta 116

**Comment by mashers** [comment]
Ahh yes, I missed this. I think checking the title ID will determine whether the boot menu is applicable to the app.
