### ISSUE TITLE
Title Launcher Rows not working correctly

### ISSUE THREAD

**Issue by Shadowtrance** [mashers/3ds_hb_menu#56]
Just noticed this issue after updating tonight (to be honest I'd never checked before as i always had 3 rows turned on).
But if you change the Grids > Rows from 3 to 1 or 2 the title launcher doesn't adjust accordingly as it should.
I'd add screenshots to show what i mean but apparently you removed screenshots. haha Thought i was going crazy when i pressed X a few times and nothing was in my screenshots folder, then i scrolled through the commits and saw the change. :(

**Comment by ihaveamac** [comment]
yeah, screenshots were removed due to them being in *hax 2.5. they had to be removed due to space reasons.

this is when you change the amount of rows *after* you load the titles, correct? that's how I managed to get it to happen.

**Comment by Shadowtrance** [comment]
Yeah I'd already loaded the titles window beforehand and was messing with different themes/layouts etc and noticed it.

**Comment by ihaveamac** [comment]
here's a screenshot I took.
![scr_17_bottom](https://cloud.githubusercontent.com/assets/590576/11367036/ddda0298-9265-11e5-86dc-972a2b741b67.png)

**Comment by mashers** [comment]
Ahh I know why this is happening. I'll work on this now.
