### ISSUE TITLE
Homebrew apps that use title launcher doesn't work properly on the latest version of GL

### ISSUE THREAD

**Issue by George35000vr** [mashers/3ds_hb_menu#57]
3DS version: Old 3DS, normal
3DS region: EUR
FW version: 9.9
HB entrypoint used: Homemenuhax, Ironfall
Hax version: 2.5
What exactly the problem is and how it can be reproduced: After updating to the latest version of GL, homebrew apps that use title selector do not work properly.It selects Download Play app instead of the app you select on the title selector.

**Comment by d4mation-** [comment]
I have the same issue, except it crashes the Homebrew Launcher for me. Renders apps like Braindump, SVDT, and HANS (when not using an .XML shortcut launcher) useless. I've tried updating to the newest version through the Updater as well as downloading the newest release from [here](https://github.com/mashers/3ds_hb_menu/raw/master/launcher.zip).

3DS Version: Old 3DS XL
3DS Region: US
FW Version: 9.9
HB Entrypoint Used: Homemenuhax, Ironfall
Hax Version: 2.5

**Comment by George35000vr** [comment]
Yeah it seems that the new update brake the title launcher and also the dpad navigation feature and it freezes the launcher.

**Comment by mashers** [comment]
The crashing should now be fixed in the latest beta. I've got SVDT and HANS booting working again now, and am just testing braindump to check that too before releasing another fix and closing this issue.

**Comment by ihaveamac** [comment]
well it doesn't seem to work entirely... I am using svdt, it shows the title launcher (meaning I have the .xml properly set up), yet it still opens Download Play.

**Comment by mashers** [comment]
I haven't yet released an update which fixes SVDT or HANS title launching. I just meant I've fixed it here at my end ;) The same fix should also sort out the issue with braindump, but I want to test it first. My cart is still dumping. Once it's done and I've checked it I'll push an update which will fix all three (save manager, HANS, braindump).
