### ISSUE TITLE
Overlay image for app icons

### ISSUE THREAD

**Issue by GoYoshi** [mashers/3ds_hb_menu#61]
I'm completely new here and I don't know how to label topics :/
I thought it would be cool to have a single (?) image as an overlay for all the app icons. With that you could apply an effect to all icons like in this image (on the right):

https://pbs.twimg.com/media/CUwDX1-UEAA5HXt.jpg

I'm not very creative right now but I think this could help to fit the different icons more to the theme.

**Comment by mashers** [comment]
Great idea, and thank you for logging it here. This would realistically need four images:
* App overlay
* App overlay (selected)
* Cart overlay
* Cart overlay (selected)

This is totally doable. The only thing I'm not sure about is how large the overlays could realistically be. The app icons are already quite close together. I could perhaps make the overlay images' maximum size big enough that they would actually butt up against each other if the full image size was used. It doesn't all need to be used though - a transparent margin could be left if a smaller overlay was desired.

**Comment by GoYoshi** [comment]
Thanks, I would be very happy with everything you just said! :)

**Comment by mashers** [comment]
Added in https://github.com/mashers/3ds_hb_menu/commit/e65ef2696ddc6a26144b427cc54411099c58879a
