### ISSUE TITLE
Include changelog in launcher

### ISSUE THREAD

**Issue by mashers** [mashers/3ds_hb_menu#63]
The gitpush script would need to wget the changlog md file from the wiki and include it in launcher.zip. The launcher would then need some kind of basic markdown parser to display the content of the file.

**Comment by RedInquisitive** [comment]
Just to make sure, this wouldn't push you over the code limit again. I think @ihaveamac is working on this feature for mglupdate, so this might (again might) not be needed :wink:

**Comment by ihaveamac** [comment]
I don't know if I'd add a markdown parser but I can almost certainly try to display something on the screen. like a selector for which beta to look at. larger beta changelogs might have issues fitting on the screen but we shall see.

**Comment by RedInquisitive** [comment]
@ihaveamac A scroll feature? Nothing to complicated, of course. I was just looking out to lighten the code load for gridlauncher :anguished:

**Comment by ihaveamac** [comment]
hard to do without making it look not so pretty (which matters to me especially since all the functionality is done anyway). but I'll have that anyway.

**Comment by mashers** [comment]
I think it very probably would push the launcher over the code limit, and I don't actually think it is necessary to have this in the launcher itself.

WRT a markdown parser, it would only need to be simple:
* Search for a pattern matching "\#\# Beta \<versionnumber\>"
* Search from this point to two consecutive newline characters followed by the phrase "\#\# Beta" (the start of the next version) or EOF
* Get the substring between these two points to get the change details for the current version number

The only other markdown code I can see in the changelog right now is the asterisk which creates a bullet point list. Those could probably stay as asterisks in the updater in order to provide bullet points.

**Comment by ihaveamac** [comment]
I plan on having it scan for "## Beta " (and changing "Betas" to "Beta"), and then picking which one to see using left and right.

**Comment by RedInquisitive** [comment]
@ihaveamac That sounds perfect! Of course, at least for longer ones, you might need to scroll up and down, but that shouldn't be too hard (hopefully).

**Comment by ihaveamac** [comment]
most of the recent changelogs have been fairly short so I don't think it will be that much of an issue.

**Comment by mashers** [comment]
Just wondering whether this issue should be closed since this is now a planned feature of the updater? We can still comment here to discuss it, it just means it won't show as an active issue.

**Comment by ihaveamac** [comment]
https://github.com/RedInquisitive/3DS-Homebrew-Menu-Wiki/blob/master/Updating/Updating-Changelog.md will be used since it's the only way I can seem to get the raw file

**Comment by mashers** [comment]
That's fine, the Wiki files are identical in both the live version in the main repo and the working version in Red's repo.

**Comment by ihaveamac** [comment]
https://github.com/ihaveamac/mashers-gl-updater/issues/3

**Comment by mashers** [comment]
Great, thanks for logging in the updater repo. I'll close this issue here.
