### ISSUE TITLE
Bad wallpaper

### ISSUE THREAD

**Issue by gocario** [mashers/3ds_hb_menu#64]
![scr_5_top_left](https://cloud.githubusercontent.com/assets/1345742/11446948/00418762-953f-11e5-9351-314cbbae15a6.png)

**Comment by mashers** [comment]
Good catch! Thanks, this should be a simple fix.

**Comment by mashers** [comment]
@gocario - please could you update to beta 128 and try this again? I don't have any erroneous titles so can't test this myself, so I would really appreciate if you could let me know if this is fixed now before I close this issue. Thanks! :)

**Comment by gocario** [comment]
Fixed, nice!
![scr_6_top_left](https://cloud.githubusercontent.com/assets/1345742/11447627/7a08c70e-9549-11e5-963e-66e431824487.png)

**Comment by mashers** [comment]
Great! Thanks for posting back to let me know :)

**Comment by gocario** [comment]
The same for when the netloader isn't available
![scr_3_top_left](https://cloud.githubusercontent.com/assets/1345742/11455138/11aa5244-964e-11e5-849a-ba0cd3714f5d.png)
.
