### ISSUE TITLE
[enhancement] Option for Homebrew and Home menu merge

### ISSUE THREAD

**Issue by Xenosaiga** [mashers/3ds_hb_menu#67]
Reserved of GBATemp requested the option to have Homebrew apps and home menu games to show up in the same list instead of listed separately.

Making this request in their behalf.

**Comment by Xenosaiga** [comment]
This can potentially be solved by just making .XML files for HANS for each game you own. But this also has the unfortunate side effect of making any games with updates unusable. And as such is just a quick dirty solution.

I don't actually see the need for this myself but I still made the request for the other person.

**Comment by mashers** [comment]
What is the issue with launching games with updates through HANS shortcuts? A better solution would be to resolve whatever this issue is rather than add yet another executable type to the menu on top of homebrew 3dsx, XML+3DSX, XML HANS shortcuts, Region4, HANS and cart launching.

**Comment by ihaveamac** [comment]
I think what is wanted is automatically generating the .xml shortcut (you know, like the included eShop one).

**Comment by mashers** [comment]
OK, but what does that to have do with an issue booting titles with updates through HANS shortcuts?

**Comment by ihaveamac** [comment]
HANS does not use a game's update data, if it's separate from the base game.

for example: if you were to launch Ironfall (and do not have 1.2), it will launch 1.0 even if you have the 1.1 update data.

**Comment by Xenosaiga** [comment]
Pretty much "Reserved of GBATemp" just wants to option to have all his/her titles, both Homebrew and Official, to appear on one screen.

It's not an issue per say. But it's more a request for more options.

**Comment by Xenosaiga** [comment]
I myself don't see a need for something that many people are just fine with.

Sorry for any time this may have taken up. Gonna close this as it's been determined that the user can just make .xml files for use with Hans.

As mashers said, and I agree with this, there's no need to add more [un-needed] code to the launcher when it's already nearly at its limit with launching code.
