### ISSUE TITLE
Returning from the settings menu crashes the system

### ISSUE THREAD

**Issue by d0k3** [mashers/3ds_hb_menu#68]
This is a new issue with b130. When trying to return from the settings menu, the system 'stops'. In some cases, waiting for a bit will eventually lead to returning to the menu, but in most cases, the power button is the only way out. N3DS on 9.0.0, using ThemeHax 2.0, if that helps.

**Comment by ihaveamac** [comment]
just curious, does using the exit shortcut (L+R+Down+B) not work if you're on hax 2.5?

**Comment by d0k3** [comment]
Well, should it work when I'm still in the launcher?

To add more info to this, I just noticed it looks like I have basically the same effect if I press the home button anywhere in the menu. Unsure about that, though, cause the home button never caused a full crash so far.

**Comment by ihaveamac** [comment]
home button takes screenshots, which is why it freezes for a bit

**Comment by d0k3** [comment]
Correct, didn't know that. Forget about what I wrote about the homebutton. The only issue is with returning from the settings menu. And the exit shortcut works, I just tried it.

**Comment by mashers** [comment]
Strange, I can't reproduce that here. Does it seem to make a difference whether you change anything in the settings or how far into the settings you go before backing out? Also could you please try deleting your /gridlauncher/hbl.cfg and see if it still does it? (Actually don't delete it, rename it so if it fixes the problem we can look into working out why).

**Comment by d0k3** [comment]
Just tried around a bit...
* Doesn't matter what I do in the settings, that system 'stop' is always there, and it's duration doesn't seem to be affected by anything.
* Deleting / renaming the hbl.cfg doesn't do anything.
* It turned out the system stop is actually never a full crash. If waiting for a long enough time, I always return to the main menu. Sometimes it even goes very quickly, but I can't reproduce it.
* From a programmers standpoint: There must be something that is done when returning from the menu. The same thing is not done upon entering the settings. Maybe the installed homebrew apps are read and updated, or something is calculated. Is there something that is fairly new? Or, is there something that could be problematic on large / full SD cards? (I have a 64GB SD card woth 12GB free)

**Comment by mashers** [comment]
I still can't replicate this. When you exit the settings menu, the current settings are saved to SD, and the menu is updated if necessary. But entering and exiting the settings should not cause this to happen - only re-saving the settings.

https://github.com/mashers/3ds_hb_menu/blob/master/source/menu.c#L1183-L1243

Could it be a problem with your SD card perhaps?

**Comment by d0k3** [comment]
I just tried this with the new b131, and the problem seems to be gone. I'm using a 64GB SD card with no file system errors on the SD card - if it was because of the SD card, it was because of it's size.

Anyways, you can close this now. Seems like I was the only one to have that problem anyways.

**Comment by mashers** [comment]
Thanks for reporting back on this issue. Feel free to re-open if it recurs :)
