### ISSUE TITLE
Cursor disappearing after selecting title launcher menu.

### ISSUE THREAD

**Issue by JJTapia19** [mashers/3ds_hb_menu#70]
I tried deleting the hbl.cfg file and also enabling and disabling the region free loader with no luck.

How to reproduce it,

Without a game card inserted.

Enter the title launcher menu and the cursor will disappear. If you press right once the cursor will appear on the first title but if you have D-Pad navigation enabled and press up once to highlight the back arrow and then press down the cursor will disappear again and if you press A while the cursor is gone you'll get a black screen. I think it launches region4.

With a game card inserted
 
If you enter the title launcher menu the cursor appears highlighting the game but if you press down really quickly while it's still preloading titles the cursor disappears.Pressing A while there's no cursor doesn't do anything.

**Comment by mashers** [comment]
Fixed in https://github.com/mashers/3ds_hb_menu/commit/8037a1b1311fd29e61454c1781dc4b934e76e0bb
