### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by d0k3** [mashers/3ds_hb_menu#71]
Don't know if that even belongs here, but at the moment tehre is no changelog for grid launcher. This page is only a placeholder: https://github.com/mashers/3ds_hb_menu/wiki/Updating-Changelog
... and on GBAtemp there is no changelog anymore as well.

**Comment by ihaveamac** [comment]
@mashers did not update the main post.

the wiki links to https://github.com/mashers/3ds_hb_menu/wiki/Updating-Changelog-Beta

**Comment by ihaveamac** [comment]
...basically it's been moved here because I'm supposed to make the updater display it. I've been slow at it  recently though. the reason it's now at `-Beta` is because the launcher will eventually be officially released, and so it's a bit of future-proofing.

**Comment by d0k3** [comment]
Alright, good. This can be closed, but let's wait till mashers sees it.

**Comment by mashers** [comment]
Thanks for this. I've now updated the OP on the GBATemp thread with the correct link to the current changelog for the beta versions.
