### ISSUE TITLE
[Request] WiiFlow like game boxes on the titles menu top screen.

### ISSUE THREAD

**Issue by JJTapia19** [mashers/3ds_hb_menu#73]
Hello mashers!

WIth app banners and fullscreen banners I think this is a possible thing to do. I was going to work on some full screen banners with the game boxes on the center to simulate wiiflow but maybe it's better to let you know about this idea first. Maybe you could add a standard size for all game boxes and make them appear on the center of the screen. I guess the tricky part would be making the other game boxes appear next to the one you're selecting like wiiflow does.

Here I'll leave a super crappy concept picture with wii boxes instead of 3ds once because I got frustrated while trying to edit a good mock up just to let you kind of know what I would like.
 
![wiiflow 3ds concept](https://cloud.githubusercontent.com/assets/15892941/11644692/a77740fc-9d24-11e5-911d-5528a8a960fe.png)

There could be a new settings option to turn on or of 3dsFlow mode.

**Comment by ihaveamac** [comment]
this is probably not going to happen due to size restrictions. mashers has repeatedly hit the limit of code that can be used (for a `boot.3dsx`) and trying to add 3D to the mix won't work. :/

**Comment by JJTapia19** [comment]
You're right. If It's possible I would be happy without the 3D and animations. Just by simulating the 3ds or another new layout without 3D entirely. If not then I'll start working on a full screen banner layout and I'll work with that. :)

**Comment by JJTapia19** [comment]
I just finished up my what I first had in mind and I think it looks great so there's no need for another feature if it takes much code and we can work with the other great features we already have, :)

![scr_29_merged](https://cloud.githubusercontent.com/assets/15892941/11647002/c48fac3c-9d39-11e5-8c53-04c7673f8611.png)

**Comment by Xenosaiga** [comment]
Why not just make a full screen Banner Package that has each game?

It would be a crude but workable fix.

And that would be a lot of games to have/make banners for.

**Comment by mashers** [comment]
I do like the idea of a flow layout launcher, but doesn't make sense to me in this case. A flow layout is horizontal only, whereas a grid has two axes. Selecting an item in a grid layout and for this selection to be reflected in a horizontal display of the banners doesn't feel right to me. A better solution for a flow layout would be for the grid to be entirely replaced with a flow layout on the **bottom** screen. That way the app/title would be selected by swiping or button-scrolling through the flow layout on the bottom, and the top screen would show the banner and/or info of the currently selected app (as it does now).

There's no way this would fit within the limited RX memory available for boot.3dsx. It would probably be better as a branch of Gridlauncher which separates the grid and flow code using ```#ifdef```s and compiles to separate targets. That way the Gridlauncher gets the code to render the bottom screen as a grid, and the Flowlauncher gets the code to render it in a flow layout.

**Comment by JJTapia19** [comment]
@Xenosaiga That's what I started to do yesterday. I've made 24 of my installed titles games but then tested and 20 of those worked due to incompatibility with hans, It took me about 35 minutes. I plan to do more today of all of my game carts. The 3ds have a lot of games but I'm thinking of opening a 3dsFlow project thread with the standard layout, instructions and that stuff. With more help I'm sure we could have at least all the really good ones. We could even design a box for homebrew apps too. I think it cold be fun.

![3dsflow](https://cloud.githubusercontent.com/assets/15892941/11659323/1294d5ba-9d9e-11e5-9d66-e792b242e95d.png)


@mashers I totally forgot about that part! The only way the layout of the first post could work is by having 1 row on the launcher selected.

**Comment by Bobesh8** [comment]
Mashers should add a second banner feature.
Like, press L to change to the back of the cover, and press it again to return to the front.

**Comment by Xenosaiga** [comment]
Not "Should". But it doesn't sound like a bad idea. Although in my opinion it sounds like a pointless feature to show a "second image/back of game"

Already so many great features but still have to careful of adding too many features as that bogs down the code.

**Comment by ihaveamac** [comment]
it is kind of a pointless feature, honestly.

**Comment by Bobesh8** [comment]
Would be good for those who have a digital eShop version of a retail game.

**Comment by Xenosaiga** [comment]
@JJTapia19, what say we close this issue since there has been a suitable solution found?
