### ISSUE TITLE
[Error] Freeze on loading too much titles

### ISSUE THREAD

**Issue by CoopLink** [mashers/3ds_hb_menu#79]
Im using this with the Homewbrew launcher cia. In the Ignore List, theres a lot of titles i dont what the menu loads when using SaveManager, but when i finish marking the apps and return to the main menu, it freeze! I need to use the L R Down B comand to return to the main menu, but the next time i need to load titles, it just freeze again without loading anything! How can i solve this?

**Comment by mashers** [comment]
Does it do it if you launch it through *hax instead of the launcher cia?

**Comment by mashers** [comment]
Any update on this? I'll close if no further testing has been done. I do not have access to CWF so can't test the CIA launcher myself.

**Comment by mashers** [comment]
I'm going to close this issue as I haven't had any further response about it. Please re-open with more information as per my comments above if this is still a problem.
