### ISSUE TITLE
NetLoader Freeze/Crash - HTTP Request

### ISSUE THREAD

**Issue by CoolApps45** [mashers/3ds_hb_menu#83]
Even though this does seem to be a universal issue, I'll list the stuff.
Type: o3DS (the very original, or you could say the first)
Region: EU
Firmware: 10.3.0-28E
Entrypoint: menuhax, IronHax
*Hax Version: 2.5 Beta

When visiting the IP and port via a browser (like Google Chrome), it would take a few seconds for the whole launcher to hang(?) completely (doesn't <i>react</i> to any input - only exception is hard resetting via power button).
A video demonstrating this issue: <a href=https://www.youtube.com/watch?v=EFpnT-NqdAQ>https://www.youtube.com/watch?v=EFpnT-NqdAQ</a>

Thing worth noting: this issue was <b>NEVER</b> introduced by GridLauncher. This was and still is an ongoing issue in hb_menu (original).

**Comment by mashers** [comment]
Just so I can try to understand this issue, what is supposed to happen when you connect to it via a web browser?

**Comment by ihaveamac** [comment]
I imagine do nothing, since you're only supposed to use the NetLoader with the 3dslink program on a computer.

**Comment by mashers** [comment]
So isn't the solution just to not connect a web browser the 3DS when net loader is running? I honestly don't understand...

**Comment by ihaveamac** [comment]
well, this is an issue that affects the original as well, so maybe check the issues of https://github.com/smealum/3ds_hb_menu ?

**Comment by mashers** [comment]
It's not listed there. I don't know anything about the protocol used by the net loader but I'm assuming it's a pretty bare bones socket implementation. A web browser will send all sorts of other stuff to establish an HTTP connection which is probably causing the crash.

The net loader uses a weird port number so it's not even like somebody might have previously had an FTP session open and then that client tried to connect to it once the net loader was running. The only circumstance under which I can see this being a problem is if somebody deliberately entered the 3ds IP address and the net loader port into something other than the 3dslink client. Which would mean that the solution is to just not do that. Or am I missing something?

**Comment by CoolApps45** [comment]
I understand that it's not supposed to be accessed via browser. However, it does something that shouldn't happen. Perhaps the connection could be rejected in some way if it were to be detected as a browser or if it were to not be the NetLoader client that's connecting to it?

A second thing that I should say is that even after the launcher ends up in that hanging state, the browser still tries to get something and it wouldn't time out. It still hangs even when I stop it from attempting to send out a request.

**Comment by mashers** [comment]
I'm going to close this as it's not an issue with Gridlauncher specifically. It's also such a niche issue which is very unlikely to occur unless deliberately triggered, and with a simple solution. Fixing it would likely require quite significant changes to the netloader code, i.e. checking for non-netloader protocols and responding accordingly. IMO it's not worth the time it would take. Feel free to log as an issue on the original HBL repo and if somebody feels like fixing it there I'll merge the changes.
