### ISSUE TITLE
Blacks Screen When Using Themehax

### ISSUE THREAD

**Issue by Jacklack3** [mashers/3ds_hb_menu#84]
It worked the first time but now when i use themehax it doesn't work.

It does the themehax stuff but then it goes to a black screen.

I switched launchers and the original works fine.

**Comment by Jacklack3** [comment]
I have a 10.3.0 27-U old3ds

**Comment by mashers** [comment]
I haven't used theme hax so I don't know if I can reproduce this. I'll try at some point though. Are you able to try with a different entrypoint to see if that makes any difference?

**Comment by mashers** [comment]
What version of menuhax are you using? And how have you set it up? I'm using it on a 10.3 EUR n3DS and it's working fine. Can you try removing menuhax and reinstalling it?

**Comment by mashers** [comment]
I'm going to close this issue as I haven't had any further response about it. Please re-open with more information as per my comments above if this is still a problem.
