### ISSUE TITLE
Multiple things

### ISSUE THREAD

**Issue by mariomadproductions** [mashers/3ds_hb_menu#85]
* Could version of title be displayed?
* Could small and large icons dumpable to png?
* Could Title ID be displayed with hex?
* Could dumping of said data be done in batch for all titles. I have *a lot* of titles.

**Comment by mariomadproductions** [comment]
Also, converting it to hex still doesn't give you a proper Title ID.

**Comment by ihaveamac** [comment]
chances are when you're converting it, you're getting something like "4000000046500" because the beginning three zeros aren't added.

**Comment by mariomadproductions** [comment]
Thanks, adding three zeros to the hex value fixes it. Sorry :P.

**Comment by mashers** [comment]
Please can you log each of these as separate issues? Managing multiple requests in one logged issue is not really feasible.
