### ISSUE TITLE
Title ID displayed wrong.

### ISSUE THREAD

**Issue by mariomadproductions** [mashers/3ds_hb_menu#86]
It isn't how it is normally formatted.

**Comment by ihaveamac** [comment]
it is a title ID in decimal format.

1125899907130624 is Cubic Ninja US, and something that the grid launcher would show. use a decimal->hex converter and you get 0004000000046500.

**Comment by mashers** [comment]
"Title ID displayed with -select- is nonsense"

Seriously? Just convert it to hex.

**Comment by mariomadproductions** [comment]
Just worked that out :P
Could it be displayed in hex?
