### ISSUE TITLE
Crashing while loading GL "Grid Launcher"

### ISSUE THREAD

**Issue by AngryEnder56** [mashers/3ds_hb_menu#90]
whenever i'm trying to open grid launcher it end up with both 3ds screens black and never loads anything so i hard reset. any fixes on this launcher would be helpful

**Comment by mashers** [comment]
I need a lot more information to investigate bugs. Like details of your device and how you're booting the launcher.

**Comment by mashers** [comment]
Please re-open with more information if this is still an issue.
