### ISSUE TITLE
add support for hb:kill

### ISSUE THREAD

**Issue by ihaveamac** [mashers/3ds_hb_menu#94]
this is a new service added in "*hax 2.6". it allows exiting from *hax to the Home Menu without rebooting.

this is the commit to the original launcher adding support for it: https://github.com/smealum/3ds_hb_menu/commit/27a7e2200ccbc51578dbaa2ddfb2ac3ffb046a41

**Comment by mashers** [comment]
Added in https://github.com/mashers/3ds_hb_menu/commit/7c424d0fdac0df25efae35624168eb4b58ab2c90
